name: GitHub Actions Demo
run-name: Project automated test triggered by ${{ github.actor }}  🚀
on:
  push:
    paths:
      - 'Project/**'
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Make the tests.sh script executable
        run: chmod +x project/tests.sh

      - name: Run tests.sh script
        run: ./project/tests.sh

      - run: echo "This job's status is ${{ job.status }}."
